'''
//  -------------------------------------------------------------
//  author        Giga
//  project       qeeqbox/honeypots
//  email         gigaqeeq@gmail.com
//  description   app.py (CLI)
//  licensee      AGPL-3.0
//  -------------------------------------------------------------
//  contributors list qeeqbox/honeypots/graphs/contributors
//  -------------------------------------------------------------
'''

'''
*******************************************************
**************  refactored by lawlez  *****************
*******************************************************
'''


from warnings import filterwarnings
filterwarnings(action='ignore', module='.*paramiko.*')

from paramiko import RSAKey, ServerInterface, Transport, OPEN_SUCCEEDED, AUTH_PARTIALLY_SUCCESSFUL, AUTH_SUCCESSFUL, OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED, OPEN_SUCCEEDED, AUTH_FAILED
from socket import socket, AF_INET, SOCK_STREAM, SOL_SOCKET, SO_REUSEADDR
from _thread import start_new_thread
from io import StringIO
from random import choice
from subprocess import Popen
from os import path, getenv
from helper import check_if_server_is_running, close_port_wrapper, get_free_port, kill_server_wrapper, setup_logger
from uuid import uuid4
from contextlib import suppress
from re import compile as rcompile
from time import time
from threading import Event
from binascii import hexlify


class QSSHServer():
    def __init__(self, **kwargs):
        self.auto_disabled = None
        self.mocking_server = choice(['OpenSSH 7.5', 'OpenSSH 7.3', 'Serv-U SSH Server 15.1.1.108', 'OpenSSH 6.4'])
        self.process = None
        self.uuid = 'honeypotslogger' + '_' + __class__.__name__ + '_' + str(uuid4())[:8]
        
        self.logs = setup_logger(__class__.__name__, self.uuid, None)
        self.ip = kwargs.get('ip', None) or (hasattr(self, 'ip') and self.ip) or '0.0.0.0'
        self.port = (kwargs.get('port', None) and int(kwargs.get('port', None))) or (hasattr(self, 'port') and self.port) or 22
        self.username = kwargs.get('username', None) or (hasattr(self, 'username') and self.username)
        self.password = kwargs.get('password', None) or (hasattr(self, 'password') and self.password)
        self.options = kwargs.get('options', '') or (hasattr(self, 'options') and self.options) or getenv('HONEYPOTS_OPTIONS', '') or ''
        self.ansi = rcompile(r'(?:\x1B[@-_]|[\x80-\x9F])[0-?]*[ -/]*[@-~]')

    def generate_pub_pri_keys(self):
        with suppress(Exception):
            key = "OWhAb0s5MlM4STVzXC4yNiJgVlBIOWw0MjspVUZGN1MlLEpIO21YOUc+VzNqQ2VdJWg7RS9QYkNJOmBuQTdJR2JDMW83cUgiMEIiREczWXMkOi5gbEIxY2NORiVvN2NCbGxbYj0jaiNnRzsqXS85a1JAQDhVM2pAO0YrcV47ZXBHSzIwMUVaRlllL1U6TTQwSUFTIkozOk1FSG04UnNfOztbUkREPEE4PCU3U2NyWTBNP0w8LmtgWVYzRDQnQTswQCVwMmJsbjk4UmsoVUE0KFEsODY4Vy0zKkJyY0c8cEBgNXUxVSIyY3MzTTFpa0IxRnRqPjg2cShaP0E4UGc5RF9OaEAxTFk/LDswUHJeRSVrXWQ8LVdDUDNEYC4jO2JxLW88LGFqNjpKK1N0QkoyODhFQ044dUNlL18vPT1bJ106aSZvN0I1RC4qODhOJDI7LyY/UjZYazRURlw2YW06S19VMTEycHVLRCk2JyVHWi46KDxIKWgvMTAtXnUxaF5TXz1gUk06MUlIPXE8XFIkIjxiTyFvJDwwPktIIic/ZzEwOFFOMGolLkhAUkdHdTc2K0MvMytraWFHXGg9YzA2ZmQoNnFMRTs8YyEiT0JoRGkqMWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ7K2J1MWk/LGJELD1BUzpIMSRkRUh1XD9AO0thdUYpI2MzQDtCT2lDTExtYkNORjApRigmYSdAO0JwbUJQVlp0QlFJczFAOydedEA8NTRlPSg1WmFFKzJGQUc7PGlBN1MlTWY3bCMwXUNlXFxANiNmTTA6Yyo4S0ddJC9sMyk8PT5CaCheJyQ/QWE4N2xXbjEwbVFvPT0lYz4uMmIucTQ8IWtSJEJOJlxtLnA+a18zLCEvTzZZL1NXPEIiKVU6ZFw7UDZVWWBGN1RYPW9CNFh0XzhuO0lLRyUiaidGJlBWKzplNCZVNjxRIUFBOU1FdTtgNHRUQFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RG91QFJyPW46ZWtrKD1gQC5yMEsqb3JGX0czIkNpPUIwRiksMyJCUDswaUJPUFt0QlBWWnRCUUlUdEYoJmB0RigmYSdDTkVvdEYpLDMqOk5dYEpAc0RzJThtJDltQk9hTSZFQ0VBUUZBP1hIQ0pSNjk4blVzV0Y+OCNYOTVaXmI6SV0lZzg3RHBLPCx0OSZERC0qOEdYNihbQ0tgQiI3cSNHPTg5SXBOMC8jYjA2bnJSTDZxTDBKNnU+WSEwbDAzO0RhUiQ9QU9dNyhFSSdyKTY9WChgQm0hLFdFYm1VJTJKLSQ4MGVaQyoyYV5KTzBnZm8kOUs9Vig8RzZNVUBtaStvQDteIUwxZkBzSEJpQWs6Ml9cO2xGPlwodTA1cmE6RUEnKz45aF1DbyQ4alVvMDUhWEMwa1g8ckRjQVouPGBxQGsxLzpTNjJjV0YmLnFYIU1BUSgqcjNGT0Y8O2ZiXGowT2NcLjV1MDorOU5jT2I9Q2E5YDZVPm9iNW1mblQ5MSkhWDY+JXVhOysjIzBBUSh1ZzhwIUAwODllPDtHQGtQRUUoaiVkPUVbRDA2U15OJDFpInBNOkghNVFBMlI3cjtmUThjN1NkcVxFRTNFREFuYXFQRGFRaiM5bTFlTTtEQ1heNjtVNkhBVDo8cTY7YCYiLm1kNkw+JCNIMUc7Ty9eOGtGLEJHW2pFTTdUc2tDOi89aGc2cHRpazloXTEsLm9wMis7RykoMTdvOy1pO2VdPEk6ZEtEOT11Lm00NnE7RTY2VjkxRzFNJy4nMmZXXCZDTjNjUTJKbVBFMyolcS46R1BVIjxdPjRnRiJwJzwkPkZRQS5udCVvN1VeNzA3O0dGYTc4LFU0QD0hKj9ERiY0bDJGZyYsMkU0YC1II2NZWjJLVmJkMDRacU4xalg3NEgiKHRnR1VsaWgubDFqWUU9LXRLO2RoVXJAU0NmQUA6Rk9RPiVeQVxHPS1YZzJjVms7Ok1FNyM3O2JcQ0JNcGouOE9RJG4yLSJJMzEsRUIxNj9aK0IyLy5BTUZdaUJoR11zS3Q3N1YqJztfKFtEOS8vMkM7L25FazAxbjM6MDIjPklAUzFpQDgzcCpUSD9fOzU7S0cvW0gjZEQtMi0+MEUxSWFpUS5uPWkoR3VROyo7L244czIpSy9rPVlFaiM8XzY+KDY8I15XRj9ydUxBOHQndEdccEspRUg9cmM4VEBYLTlNQWtrOU1lYzU1cmoxLkA6V1BNRz5EbW82W0Q0RzltQl0vJD5FOjE6TSFbLzc6VT90MDJIUl03bz0yJjZVRl5lREhVTC0yZl5aQ0VBXVJRQzItT1I4UVNBXTY9T0BZPUAsI0A9XGE2RDxFKWdNOkohPD1BSTsxTUVDRiMmN1QrRDVAViVORUUtPzpuRz02T0ZDSkpcZzFqIV84NzhlPk1EZWhzWDpkVC5dRCxPdGIxZmQ6aTpLKUhmMUhBNlI8YD0zIjY+JFguRiVDRk4zK0daWjwsR1EnMU4/JDU6L2NDYDlOYT5pMUgvb1xCbCRzSDdzVERqPURvbGg7YU9ZRDtiVStKPER1dDJFSCFbKToyRF5AQVFhIVtFYm5CY0NJVilYMkhXQ2oxMVcrQDc2K0xeO2JNNFBFXS5XRz1gUU1uR3Jda2JHI01tWjtjYkpnR3VlUUpGQVlbdTV1Qyc6M0RgOXRDL1Q3ZyQ6OEplN1doZFk4OEUqXEByRyI5RGYvP188YlpcdUdaXCE4QjRsNl4wSmtYRTdua2E+OjNUP0BBVGhabz1BKHFIMi5TSV5AVzVhcjpmZkdiPFhORE87LkUnZ0FQI3MiOjMmbS5DMCJDajxkNy9XPFxlSzU9W3RyKTBKdWRSMyxFJiNAUjtfZjdrWztHRkQjPkczSTNETjtmbSVVNnBgQ1c6aSRJcEFsIUFGPiZlWG1AUGdxXTpJMCZERC9XaU42P3VGQDAyI2JSPidGKE1HWjhpSDotaUdbN1E9Q09BOWAsY0c+cUNYOVFzJDtCNi1zSjYkPWFjMkg8JUA6LmVXKzZTYE9pOmpRcidDS09KKEMuRF0xNiNdazlBaVcxTUc7V0FvMitCU2JGYF08LzxjO25uOFQvaWk7XyosXDBmIW9jQTJKRlQkO1gmVT1cMyRpLnJdLTw6MjJPUUIwcDAzMSxgIUo9WjpJWjJkMC1LOWg3Jzw6R3VwL0JRbU41SCE0IT49QHRHTjlNbUtdRSg8NWMwMkY2ST06L1lXRV8lXWxDMkBISzBPXFdsOTEpIUI3NnJZLTBqN1knPidiJ2RHXVpEODZxTCpPN3MkW2E4TVgiSzwrZkIsRiJoI19DK0VkZTswLDlGPCw7bkZDLk5TRz1dU0k6OGhhalhIITRjU0clc1o7MmNFQChDSi5UL0JQTEBXLnNaN3A6K0xCcDVyM2UvLnEyLlFAbU9pWz0oLSxnMmAjLDkyLGVaKj0mRUlSQVM+cSs2Iio4VkEyLmdrN2wiKGQ9Xmw+RDZvZW1LNnBgVktIOEs7NEA7XFldNnFeQyZBN0tJZTtiS1NRNldlN2JFRnBuPDBQIUxSJDhRcE86ZFxcaztnPD1ZQ2dmZ2kxMT4zKEZZWyo3PEI1MjJDSTpCUzc5KSQ2ODJGKydBTjNMWDhuaEAkQFNEI2Q8LTonIUJQXT5ERz1hVC9FIWc4VzY7MDZzMUpDOzozQ1p0Wz4lOlcvRGJEbHJERGFAaTgyYlFIPVtrYk1EYDtXMjkybz41MFE4ZGs3U2NUVUBTQlswOkgqUHAxTzxxYjhRUTczQWsrW1JIO2NJdTZ0Sy5hQFBocHM4bXVSXUJrTSRqSD9yWTAyRl4iZDxdRmJqO2BSMD5HPXQ6aDsrM2NiOGkxSGFIPmQ+M0REV2s6QlE/S0o1dVRbRTFlYCphO2YsSCE3VD0pJ0JOJGZCQy4yVyhDLnA5OEE3OU9bMDApXV1AcCpuNTJITkY6PUNjOD45aEombEMzPUFPQ2lGMzFHWD5TSSQ6W2xoODgpSTI7Rk5Hczg1Ols1Q2g/YT1EYVMpJjFqKV9UOGpjJGRDZGBQYzxcUlskRmAxbzw8RWBAKUJtKWckRV0+Z09EZi8mdTpqR3VXR1JBIlcxSCZEbT4jJi4yR3I5aDs3b3I7XDhPbU49PT49UGRAOHEvJjMoN0BkRihuVEQ4OWRYKjJmaWU7Rz5EK1xHXSQ4YkVBcEwiRlwibyE+JW49YzdXKCtyQGwtUy89dVRWXTJHQGRiN3FrXnM9YElWJ0BrZ245QFI+QiE8YlFEKkd1LWU8MGxdWk87YVdOOj1GKyJHMWR0PlozJmw0YkQtQ0tYOy40UWI9KTFmPUc9RyZHOWxgUjU3OkxDMkNKW1RCRl5vWVU7X14lPzJEVDtJRUdCTWU8LTJldUBTQ1RVRC5ac0JHJjovZEVEMGhBNnFvT0kkPEQlXzhvUlgjNlU9Ujw1cXRvLDduUk1kOi9hciQ6ZigiR0FvKUMvPSlwWVlERzNsQTFKVUdAOGlDRWM5Zk9zaEZbOUZuN3MtSWY1dUJDVUNDNHU9Mi09bTcxMkQvVDhNPGRsNjtxY0pHOlI2O0Z1VyZjN3AwSkU3c1tzLkNJKWA7Oi91QEhIOCYhMjtfcWk7MS8nUSg8YW5qRENOKWRHRUdaJWBELlJdPzdTXDUnRUMiZV1BNDAhRkQsaU1uR1k5bl1DZGAsYkE3ST85PENeLC85TSZFNT1CVDlbOTQ6XlhDLjMmQDNDY0BtO2MjdGMzKks4Z0dcMFdIPGNxU0IwL0BRK0RjQkpOMy1SX1ZFSEZvUTpjVUZORCwhTj9GRUxiO0dVbVlrLm5ObzQ5Z2dtQ0ZcLCk8MmNXZ1k6alBucDwoZjIrJD5zPFU2OnMxRzppb1RUR0BrcVRGdUQqaUNkaGxRRls3bEVGPlBnMzEyOm5dMGtiXS5AUjRaYjBrWSlnOWt1ViUxZE8jZzBRZ05ERUNpSztCYVNaVTlRUCZgRkFZWGEyYFloRURLXWVSOS86UjI4UE4vUDovPkxaMklmQyg5MSkhQjY8WjYjLnJdJDIxMDcxbTY4RDRiQytoU1ZEYUFWPUYoLEpnNm8/cWFIOjlOLkRmbykyRWAiWiY3Umg4cDZbPFRnRkF1Ljs8RlxFb0JsU0RYMDU1VCE7S0Zda0YnKjxMR3JdaEUzLUIiLzBsTFQ0QU1kaicwM0txc0g4QUpnRlxaTyhELToiNUBzKGRUMylOIk9GRCFwNzg4TWpdRCkiW1g4blRucTIuZyNnRShqNVYzSEpZPkZEaiZyO2ZPYGNERjcmdSQ9dHFZOWhSM1E4N2JNPDZaJD0uR14rMVAwZVtdY0QoQEFVMGhGLShHO1dHUEUrKjNJQW9nZGhEKVAtbToyIjwkRUVRKC1BMmM7Oy5sOVwtNjQsWV9AV1lGYDloVChVMmVjYDFAOjstPj1Da0hOPEkvYVpELCFNbENLRWwoRCwhVyI9QSoxJjc6ZWhmQDg6TlI2WmwxSkFRV0pSRyYoOFYwZ2xAYTdzJWxlOUo5IW47RmtAUjNEV0NcOWlIJUhBN29ScUE0JitROklvSWA7Yy5SREc/SFhsMU1BVVs5UFszV0RJW2EkQi51XSEwNUVMQDhQKU1dOTJTOEk1c1wuMjYiYFZQSDlsNDI7KVVGRjdTJSxKSDttWDlHPlczakNlXSVoO0UvUGJDSTpgbkE3SUdiQzFvN3FIIjBCIkRHM1lzJDouYGxCMWNjTkYlbzdjQmxsW2I9I2ojZ0c7Kl0vOWtSQEA4VTNqQDtGK3FeO2VwR0syMDFFWkZZZS9VOk00MElBUyJKMzpNRUhtOFJzXzs7W1JERDxBODwlN1NjclkwTT9MPC5rYFlWM0Q0J0E7MEAlcDJibG45OFJrKFVBNChRLDg2OFctMypCcmNHPHBAYDV1MVUiMmNzM00xaWtCMUZ0aj44NnEoWj9BOFBnOURfTmhAMUxZPyw7MFByXkUla11kPC1XQ1AzRGAuIzticS1vPCxhajY6SitTdEJKMjg4RUNOOHVDZS9fLz09WyddOmkmbzdCNUQuKjg4TiQyOy8mP1I2WGs0VEZcNmFtOktfVTExMnB1S0QpNiclR1ouOig8SCloLzEwLV51MWheU189YFJNOjFJSD1xPFxSJCI8Yk8hbyQ8MD5LSCInP2cxMDhRTjBqJS5IQFJHR3U3NitDLzMra2lhR1xoPWMwNmZkKDZxTEU7PGMhIk9CbFpnQjdsV24xMG1Rbz09JWM+LjJiLnE0PCFrUiRCTiZcbS5wPmtfMywhL082WS9TVzxCIilVOmRcO1A2VVlgRjdUWD1vQjRYdF84bjtJS0clImonRiZQVis6ZTQmVTY8USFBQTlNRXU7YDR0VEBScj1uOmVrayg9YEAucjBLKm9yRlxkLV1AVWpZJUBTMGFIMTIoL2U4OSUnZzEzPzktOWwhTmpFQ3NrPzFpdEhzREcrayw6SlhHbzduQChyRl08Qkk7Sm4uMD4nTj5KQ01SKixAN09hLEVfKD1RRF9FYjRDSUJtcDdtb3BFOUxOX2w8XFxEWDNIJThUR0BhNjhCNXI1YTAxJy9NNj46UjokP0JyPzc1ZWFaR1ZMaks9I1dLRUA1MSxnRiVlU0U8YE5nVTxiIk5SRigmcyk1cjtKUDNHREUvNm9RZiQyZnBvdDMlbzUtNzwndDo4UE1scTdnXyswMGVbMCw4MjRhUkJRJGovQjMmLm9Aa3BlUzdRND09MC5VWFlHXCdmKEQpbCNUPEUhczYxYmBBbDkwbD8wN1NIcy5IPD1dODlnXzNqNzZxOEg7K2o4QkIwcDViQWwxcC9CNFkiMDhQNChqQTRVcks8LU1xZzEyb29fMmN0NXQ4NCwtaT0+WGVNPUFMaHEzK09tRUFRKlNYRSgzV0EySztiKTsuYU45QlEkNylAU00jazZyR2EvRiRgXHA5NGAqODAxJk5eODFSIyxCTmVKUDhVISIuR3RMWU1ES29ZYj1bbFM5QG5vZyE8KCcsajxEPy8iJDdmLmZHdUA3VztiJ1xCSDtlTlpCaSUqQUA5UEhBPCgnNiJCTD5CS0EyQGRnR3JLX1s2dS1kTjdsRzQrQDVxOkc4NUQhNzFLSEdZNiQiYksxKCVgOjNAZGdFQG4nbUc5TFdfZjduJCowOTQ8LWlHJkJUYi5sS21gOUsiazI3c1QsTTwmU2hwODIiTDJBMkpVUzc8cj9kODljWGQ5SWhvNEVIKT4yMixkcEJBUlw+UjwrMDZeN3A5T3IwbT8hMUIvYGdOPCk3M3M9W2Q0Ikg+JDI6REZtNWNHcjhUPEUmJzRZODQlSnBEYCk2VEJRW0hrQVUmRCs9W2JocUE1YiFUPChlciRGJj9wNjtfTGEmQi5sblk9KDRkRzplM2xMPUYsM0w1dU1iajEzbW5NQi9OZTtFQUwnUkUlPUcnRUh0TTZBUG1HJCQ4allXRicxLnRHPy46OUFqVEhQRDAvJ0ZGKEI4WzJnQjE/RyZfUyJAUyhROzwob3RvOmVYXGRHIVMtNURkZDBbQDxZTFxGQDFAREc+MzxfN2dgcys5aSM+JzxDTEQ8MyVuJ0k5TGhydTtGPGNMQ01tOWMyKWZQMjdXQzpCPEdIOEVAUydXajxDMS8nMTA/ayc5M0cjOD0maTNzMGkoQHI7LlUpMERLLypKOGspXiU+JTImJkgjUnFKODlbSUQ4byUxPEZZbjJbO0ZPSy1FYzVfY0IyQ3A3MyxNUSpFJjpUaEVES01XLmwwMV1GXU1GYjIqdHBfPWBbLFY7KWkmWzpmTToxN1BmJFZIOzdDYEg7JUkkQyw3ZVxDMiVLZjlMakFTQHAhWSc6SydTYDFLLXRHMkg8W1dBb1ZjRjhQWChYMGtGTC0kP0JyVUQvMlU6MkUiWitGWVtKXj0lLCxQQVEpNkRFSDNzT0JqI0k6ODltNDhFY3RBa0A4ZzVYRS1ZSnM3cyVVJDZVPVI8NXJoYjUuciV0K0IqcHQ/MyhBJGxIOlZnaERJW1RYOk4oLEhBbGBWZ0ZFZ25nNzskN1I7KHNnYTIrTEByPF9kajNAcUJncUA5Py9nNjhgOi9FRk5scUVfb2duQWxdN01CTWk4Lzk0XltyOmVsJSU9X151PTBpaU5pRkIxLzVGQk0rJ0Z0YmRQR1c5TUs6Z3VhRUVDVlpOQzM0KicyKiN0Ozg1alZOOklJTiIwMlFIbDFNMEYlPCpGOWBAOkQmajwpNWYkRkRZcik2cGMvckIubG5lPCpGS0o9KlJcZjNETWtPNzdLNzo+JURrdTg5XCQwRShrSUhAcVRqXDsqZkBVJDh0bU07R0toZERGNjBzQTVJU2dIIyRNWzdWWUclO0YsOCZBUypxaDhwPC1tOUpvOiIyZyczcjhRS2JKRCtTWWpDZjtqMDZTVT8+Qk9pckJINCFHOTYhNmNmNm48NGhELCtoJDc7InF1PT5EZDNEY28jQTFIL0s5Nzg2PC87R1QyYkZELGwiMTNtJiE6S1U0SDxENjdEREsmKjQ4MiFhbEg8Ok1kRC9yL3RBU1EkbTZTTXFeOytqOEI7KzNjKjwmJVFYR1pvRTI8SHJVVDNDSEc1O2IocGc5aEAqN0A4cGxDOG9sW3AzR0wnUzkyVGIkRCxiPFk+JiRUUTpnJGd0Q0okOW08ZEBrWzozTEFGNlQ3cTowbCdFXD1fTVBIQkllQE4yLDVaQ0BSMmVxRlhwb289KD1PMi5wJC8iRSZUUmQ3NVwiZSQ8TCk3SD1eYyxHc1BrLzk0VGJsOGsxWDpGQk4nbDlMTG1SNzc5SHNFZEJRVTsuND82R1hQMiVIIjpFJUE1YyxqOTEpZyIySzw9X0JKPHNgPXBkJDJHPkxZOTwpXCReOk1hSDAxR1dCWjxjcDAjQy9tOTpAVlw9czY6Rm0uOGs6YTgzRnQwSDhQM1x1OWskZUBFRSUnPDxiUTsmRkVeOzREZj8lczthTy84M0FYPyE7RTczR0FtL1xHOjJgY11Acj0uX0QrSFIsMWcqOjg4VC1QLDpKNFlxQko9QlxHPUdBIjxGU1giQG8jJS86R1s8N0g6XzBGQjRhWGo6TzVxbT0lJFVxN3ErO2w6LmVyM0dcTGYmQjZubCpEKU9qTTAzMSZHO0gjU0I6M1Q+dTV1Qyc6QmhDNCM7TDM3bERKaDldOTUmPzYkOi5USz1ZcmZyODVqQSg1dDRnZj0oa01qMDU8cGM4U1VwUDBrPV42PFxISSwxMU9JLzMmWGkvNldkbDk4NTJdTEJQTVssMkpkPktFSGpmUkJGNzQrOmU1OC87YzYlQTBNInFoO0pdckg3ckxiKzY4V2dgMkctPipFLDdwZkQscj5uR11kcTtHdVwkST1fVyVHMktDYzQ7L14+QjAyUXBtREtsTSI6LD1lMzFLbU9UQXBIN1k4NFFgUjtGc0FuRyQkSjY6TFI0QDIpbiQ4QDw2LV43bkBrcDxdPik5PUVkUD1HQmUiI0A8IjR1QHMoPTE7ZCpsQkZATC4rQW4qWWMxMFFWPzpjOyFcPF8kayE7ZCIqRDJJZUk/ME9kQHAySEZMMDBSNkpcQU1KMG83OGxRNThtJEM/O0ReZ0BDY0ZEIzxjKSNPJDtrNVJEY15eUz1hKj4pRz4zKkVCMTY5UDhTXy1vRUhQYzkzKV9PZUIvVk1jOWxYb2c5MnAiSEdbYT9fREpgdWg4OVNpS0A8InRNPENCUD1AMSQlUURiPXRHOTEpIUI3NnJZITplKyxtN251dVlCMkRFJTFoTFFCRyNyXU8uckokV0MsOFVUPF8+OGI9JXRZMjMtQE1xMitNZEI9Wz5uP0RlZlx1MmA0XVhDR0tbTkVDaGZYMExBXVVIP1VsTkI2SDcrOGszI3NFQ1k9TjsvOEk1PSYpYjpBVTYlJ0UpU1EkMSw7Tlw7Y1tAJ0UsMERfPUUvMGI8YylEZjAxSl1eOWxXSUNCNE9EJTFNcCxOO2c6cW02WW8vLUdbdDs9RkIoaDREYk5gK0ghIjNeRyJaN0EzLDFtIzxCM1E4MixkPUE9I2FBXyRAJC9WOy0lZ0M6Yk9TRTJLKVBpRSZgJi82Py4qQTtHXUEzRC9FITtFSEg+LC5zTlJeMyVJUig2cXAnLT4nM0QsQyxdLWw9Jj0zPTIsbTQuMSglby49W0dfPkBTaC9FRUhjIzoyS2d1NkJsJDRLRGZuPyczLTZ1NjIpOG9nLmt0Xls7ZHIlKzIpL2BVN25tYlZDR1w9ODc1L2plSCNaREJFYlBrczwocUBNQjY3IUMwSzIiMjZaLidfMkc1ZkhGXCw7LDZyJE5qMWNBaTpHPXQ6aDsqbkdEMElxKlFBaG1GXkZbQGlXLnIkXnRAVytQVzg5ODVJQWplTDkzSTQrSkVjNikkLnJuS0RAUmBoKTwndHFMRGZlclY8KW1FcjsvKCNxMyVudWg3VCs6YjpOS1dVN1g3IjU8XUc1OzhoazZwQHFASyskODVPODc9JGFnNzxNQDsxMlUvczhSbG1DPXVdQUdAV1o2TDloOSkzR0FUJy05aEslUkNjLGcuOmlLKi1Hcl1xVEBydVdJMmNGXVQ3VyhSZDxzaUxuNjs6Ki1BazZLLUZbTCJVOjNfIyZHVkxqcENNYlJXQmVgMTc+J0RpKi5yXHArOFMzJD9FYyFeMD4jJmFFM0g4MXQ3cT1QNzkuTWhmQjBscWFBUl1hWEQsIVo4MilmNVlAVVdcKUc/QUVVRSloNCs4bzc5bThTX0JwPGMoUSc7LTZKJTtGUC5hPSgrajxEKnJHQUclRmNkQTlNYGw6LCwtRENJYEpMMDIrI2sxL15ZUzBmYCQpQTUtIUJDMUxzakVGX0VsPF9sOCsySCpJbkA8WWovOE1iJDpDLnJENzIvWm9GQlAwImRIN3MlbQ=="
            print('key', key)
            string_io = StringIO()
            print('string',bytes(string_io))
            #key.write_private_key(string_io)
            print(key)
            return key, string_io.getvalue()
        return None, None

    def ssh_server_main(self):
        _q_s = self

        class SSHHandle(ServerInterface):

            def __init__(self, ip, port):
                self.ip = ip
                self.port = port
                self.event = Event()

            def check_bytes(self, string):
                if isinstance(string, bytes):
                    return string.decode()
                else:
                    return str(string)

            def check_channel_request(self, kind, chanid):
                if kind == 'session':
                    return OPEN_SUCCEEDED
                return OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

            def check_auth_password(self, username, password):
                username = self.check_bytes(username)
                password = self.check_bytes(password)
                status = 'failed'
                if username == _q_s.username and password == _q_s.password:
                    username = _q_s.username
                    password = _q_s.password
                    status = 'success'
                if status == 'success':
                    _q_s.logs.info({'server': 'ssh_server', 'action': 'login', 'status': status, 'src_ip': self.ip, 'src_port': self.port, 'dest_ip': _q_s.ip, 'dest_port': _q_s.port, 'username': username, 'password': password})
                    return AUTH_SUCCESSFUL
                return AUTH_FAILED

            def check_channel_exec_request(self, channel, command):
                if "capture_commands" in _q_s.options:
                    _q_s.logs.info({'server': 'ssh_server', 'action': 'command', 'src_ip': self.ip, 'src_port': self.port, 'dest_ip': _q_s.ip, 'dest_port': _q_s.port, "data": {"command": self.check_bytes(command)}})
                self.event.set()
                return True

            def get_allowed_auths(self, username):
                return "password,publickey"

            def check_auth_publickey(self, username, key):
                _q_s.logs.info({'server': 'ssh_server', 'action': 'login', 'src_ip': self.ip, 'src_port': self.port, 'dest_ip': _q_s.ip, 'dest_port': _q_s.port, "username": self.check_bytes(username), 'key_fingerprint': self.check_bytes(hexlify(key.get_fingerprint()))})
                return AUTH_SUCCESSFUL

            def check_channel_shell_request(self, channel):
                return True

            def check_channel_direct_tcpip_request(self, chanid, origin, destination):
                return OPEN_SUCCEEDED

            def check_channel_pty_request(self, channel, term, width, height, pixelwidth, pixelheight, modes):
                return True

        def ConnectionHandle(client, priv):
            with suppress(Exception):
                t = Transport(client)
                ip, port = client.getpeername()
                _q_s.logs.info({'server': 'ssh_server', 'action': 'connection', 'src_ip': ip, 'src_port': port, 'dest_ip': _q_s.ip, 'dest_port': _q_s.port})
                t.local_version = 'SSH-2.0-' + _q_s.mocking_server
                t.add_server_key(RSAKey(file_obj=StringIO(priv)))
                sshhandle = SSHHandle(ip, port)
                t.start_server(server=sshhandle)
                conn = t.accept(30)
                if "interactive" in _q_s.options and conn is not None:
                    #ssh header
                    conn.send("Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.10.60.1-microsoft-standard-WSL2 x86_64)\r\n\r\n")
                    current_time = time()
                    while True and time() < current_time + 5000:
                        conn.send("/$ ")
                        line = ""
                        while not line.endswith("\x0d") and not line.endswith("\x0a") and time() < current_time + 10:
                            conn.settimeout(10)
                            recv = conn.recv(1).decode()
                            conn.settimeout(None)
                            if _q_s.ansi.match(recv) is None and recv != "\x7f":
                                conn.send(recv)
                                line += recv
                        line = line.rstrip()
                        _q_s.logs.info({'server': 'ssh_server', 'action': 'interactive', 'src_ip': ip, 'src_port': port, 'dest_ip': _q_s.ip, 'dest_port': _q_s.port, "data": {"command": line}})
                        if line == "ls":
                            conn.send("\r\nbin cdrom etc lib lib64 lost+found mnt proc run snap swapfile tmp var boot dev home lib32 libx32 media opt root sbin srv sys usr\r\n")
                        elif line == "pwd":
                            conn.send("\r\n/\r\n")
                        elif line == "whoami":
                            conn.send("\r\nroot\r\n")
                        elif line == "exit":
                            break
                        else:
                            conn.send("\r\n{}: command not found\r\n".format(line))
                with suppress(Exception):
                    sshhandle.event.wait(2)
                with suppress(Exception):
                    conn.close()
                with suppress(Exception):
                    t.close()

        sock = socket(AF_INET, SOCK_STREAM)
        sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
        sock.bind((self.ip, self.port))
        sock.listen(1)
        pub, priv = self.generate_pub_pri_keys()
        while True:
            with suppress(Exception):
                client, addr = sock.accept()
                start_new_thread(ConnectionHandle, (client, priv,))

    def run_server(self, process=False, auto=False):
        status = 'error'
        run = False
        if process:
            if auto and not self.auto_disabled:
                port = get_free_port()
                if port > 0:
                    self.port = port
                    run = True
            elif self.close_port() and self.kill_server():
                run = True

            if run:
                self.process = Popen(['python3', path.realpath(__file__), '--custom', '--ip', str(self.ip), '--port', str(self.port), '--username', str(self.username), '--password', str(self.password), '--options', str(self.options), '--config', str(self.config), '--uuid', str(self.uuid)])
                if self.process.poll() is None and check_if_server_is_running(self.uuid):
                    status = 'success'

            self.logs.info({'srv': 'ssh_server', 'action': 'process', 'status': status, 'src_ip': self.ip, 'src_port': self.port, 'user': self.username, 'pass': self.password, 'dest_ip': self.ip, 'dest_port': self.port})

            if status == 'success':
                return True
            else:
                self.kill_server()
                return False
        else:
            self.ssh_server_main()

    def close_port(self):
        ret = close_port_wrapper('ssh_server', self.ip, self.port, self.logs)
        return ret

    def kill_server(self):
        ret = kill_server_wrapper('ssh_server', self.uuid, self.process)
        return ret



if __name__ == '__main__':
        config = {
         "port":22,
         "ip":"0.0.0.0",
         "username":"root",
         "password":"admin",
         "log_file_name":"ssh.log",
         "max_bytes":10000,
         "backup_count":10,
         "options":["capture_commands"]
        }
        qsshserver = QSSHServer(ip='0.0.0.0', port=22, username='root', password='admin', options=["capture_commands"], config=config)
        qsshserver.run_server()
